db.orders.insertMany([
    { "_id": 1, "customer": "Alice", "items": ["pen", "notebook"], "total": 120, "status": "delivered" },
    { "_id": 2, "customer": "Bob", "items": ["bag"], "total": 450, "status": "pending" },
    { "_id": 3, "customer": "Charlie", "items": ["pen", "pencil", "eraser"], "total": 90, "status": "delivered" },
    { "_id": 4, "customer": "Alice", "items": ["notebook"], "total": 60, "status": "pending" }
])

// Que-1 Write a MongoDB query to find the total amount spent by each customer where the status is "delivered"

db.orders.aggregate([
    { $match: { status: 'delivered' } },
    {
        $group: {
            _id: '$customer',
            totalSpent: { $sum: '$total' }
        }
    }
])

// -------------------

db.sales.insertMany([
    { "store": "A", "month": "Jan", "items": [{ "name": "pen", "qty": 10, "price": 5 }, { "name": "book", "qty": 2, "price": 50 }] },
    { "store": "A", "month": "Feb", "items": [{ "name": "pen", "qty": 5, "price": 5 }, { "name": "book", "qty": 3, "price": 50 }] },
    { "store": "B", "month": "Jan", "items": [{ "name": "book", "qty": 4, "price": 50 }, { "name": "bag", "qty": 1, "price": 200 }] },
    { "store": "B", "month": "Feb", "items": [{ "name": "pen", "qty": 20, "price": 5 }, { "name": "bag", "qty": 2, "price": 200 }] }
])

// Que-2 Find the total revenue generated by each store, and also list the top-selling item (by quantity) for each store.

db.sales.aggregate([
    { $unwind: '$items' },
    {
        $group: {
            _id: { store: '$store', item: '$items.name' },
            totalQty: { $sum: '$items.qty' },
            totalRevenue: { $sum: { $multiply: ['$items.qty', '$items.price'] } }
        }
    },
    { $sort: { '_id.store': 1, totalQty: -1 } },
    {
        $group: {
            _id: '$_id.store',
            topItem: { $first: '$_id.item' },
            topQty: { $first: '$totalQty' },
            totalRevenue: { $sum: '$totalRevenue' }
        }
    }
])

// ---------------------
db.products.insertMany([
    { "_id": 1, "name": "iPhone 15", "category": "mobile", "price": 1200, "rating": 4.7, "stock": 30 },
    { "_id": 2, "name": "Samsung Galaxy S24", "category": "mobile", "price": 1100, "rating": 4.5, "stock": 25 },
    { "_id": 3, "name": "MacBook Air", "category": "laptop", "price": 1800, "rating": 4.8, "stock": 15 },
    { "_id": 4, "name": "Dell XPS", "category": "laptop", "price": 1600, "rating": 4.6, "stock": 20 },
    { "_id": 5, "name": "AirPods Pro", "category": "accessory", "price": 250, "rating": 4.3, "stock": 50 },
    { "_id": 6, "name": "Logitech Mouse", "category": "accessory", "price": 80, "rating": 4.4, "stock": 100 }
])

// Que-3: 
// 1. Write an aggregation query to find the average rating and total stock value (price × stock) for each category.
// 2. Then, decide and explain which field(s) you should create an index on to make this aggregation most efficient — and why.